use wasm_bindgen_test::wasm_bindgen_test;

#[wasm_bindgen_test]
fn test_generate_tournament() {
    for (input, output) in [
        (2, vec![None, Some(1), Some(2)]),
        (3, vec![None, None, None, Some(1), None, Some(3), Some(2)]),
        (
            4,
            vec![None, None, None, Some(1), Some(4), Some(3), Some(2)],
        ),
        (
            5,
            vec![
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                Some(1),
                None,
                Some(5),
                Some(4),
                Some(3),
                None,
                None,
                Some(2),
            ],
        ),
        (
            7,
            vec![
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                Some(1),
                None,
                Some(5),
                Some(4),
                Some(3),
                Some(6),
                Some(7),
                Some(2),
            ],
        ),
        (
            8,
            vec![
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                Some(1),
                Some(8),
                Some(5),
                Some(4),
                Some(3),
                Some(6),
                Some(7),
                Some(2),
            ],
        ),
        (
            12,
            vec![
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                Some(1),
                None,
                Some(9),
                Some(8),
                Some(5),
                Some(12),
                None,
                Some(4),
                Some(3),
                None,
                Some(11),
                Some(6),
                Some(7),
                Some(10),
                None,
                Some(2),
            ],
        ),
        (
            32,
            vec![
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                Some(1),
                Some(32),
                Some(17),
                Some(16),
                Some(9),
                Some(24),
                Some(25),
                Some(8),
                Some(5),
                Some(28),
                Some(21),
                Some(12),
                Some(13),
                Some(20),
                Some(29),
                Some(4),
                Some(3),
                Some(30),
                Some(19),
                Some(14),
                Some(11),
                Some(22),
                Some(27),
                Some(6),
                Some(7),
                Some(26),
                Some(23),
                Some(10),
                Some(15),
                Some(18),
                Some(31),
                Some(2),
            ],
        ),
    ] {
        assert_eq!(
            songsort_wasm::tournament::generate_tournament(input).bracket,
            output
        );
    }
}

#[wasm_bindgen_test]
fn test_modify_tournament() {
    let mut tournament = songsort_wasm::tournament::generate_tournament(6);
    assert_eq!(tournament.get_pair(), ((9, 5), (10, 4)));
    assert_eq!(
        tournament.bracket,
        vec![
            None,
            None,
            None,
            Some(1),
            None,
            None,
            None,
            Some(1),
            None,
            Some(5),
            Some(4),
            Some(3),
            Some(6),
            None,
            Some(2)
        ]
    );
    tournament.pick(9);
    assert_eq!(tournament.get_pair(), ((11, 3), (12, 6)));
    assert_eq!(
        tournament.bracket,
        vec![
            None,
            None,
            None,
            Some(1),
            Some(5),
            None,
            None,
            Some(1),
            None,
            Some(5),
            Some(4),
            Some(3),
            Some(6),
            None,
            Some(2)
        ]
    );
    tournament.pick(12);
    assert_eq!(tournament.get_pair(), ((3, 1), (4, 5)));
    assert_eq!(
        tournament.bracket,
        vec![
            None,
            None,
            None,
            Some(1),
            Some(5),
            Some(6),
            Some(2),
            Some(1),
            None,
            Some(5),
            Some(4),
            Some(3),
            Some(6),
            None,
            Some(2)
        ]
    );
    tournament.pick(4);
    assert_eq!(tournament.get_pair(), ((5, 6), (6, 2)));
    assert_eq!(
        tournament.bracket,
        vec![
            None,
            Some(5),
            None,
            Some(1),
            Some(5),
            Some(6),
            Some(2),
            Some(1),
            None,
            Some(5),
            Some(4),
            Some(3),
            Some(6),
            None,
            Some(2)
        ]
    );
    tournament.pick(5);
    assert_eq!(tournament.get_pair(), ((1, 5), (2, 6)));
    assert_eq!(
        tournament.bracket,
        vec![
            None,
            Some(5),
            Some(6),
            Some(1),
            Some(5),
            Some(6),
            Some(2),
            Some(1),
            None,
            Some(5),
            Some(4),
            Some(3),
            Some(6),
            None,
            Some(2)
        ]
    );
    tournament.pick(2);
    assert_eq!(
        tournament.bracket,
        vec![
            Some(6),
            Some(5),
            Some(6),
            Some(1),
            Some(5),
            Some(6),
            Some(2),
            Some(1),
            None,
            Some(5),
            Some(4),
            Some(3),
            Some(6),
            None,
            Some(2)
        ]
    );
}

#[wasm_bindgen_test]
fn test_play_tournament() {
    let mut tournament = songsort_wasm::tournament::generate_tournament(6);
    tournament.get_pair();
    tournament.pick(10);
    tournament.pick(11);
    tournament.get_pair();
    tournament.pick(3);
    tournament.pick(6);
    tournament.pick(1);
    assert_eq!(
        tournament.bracket,
        vec![
            Some(1),
            Some(1),
            Some(2),
            Some(1),
            Some(4),
            Some(3),
            Some(2),
            Some(1),
            None,
            Some(5),
            Some(4),
            Some(3),
            Some(6),
            None,
            Some(2)
        ]
    );
}
